routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('students.index');
});

Route::get('/students/grafik', [\App\Http\Controllers\StudentController::class, 'grafik'])->name('students.grafik');
Route::resource('/students', \App\Http\Controllers\StudentController::class);

app/Models/ScoreAspect.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ScoreAspect extends Model
{
    use HasFactory;
    public $timestamps = false;
    protected $guarded = [];
}

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    use HasFactory;
    public $timestamps = false;
    protected $guarded = [];

    public function getKey()
    {
        return "nim";
    }

    public function getRouteKeyName()
    {
        return "nim";
    }

    public function scores()
    {
        return $this->hasMany(StudentScore::class);
    }

    public function getScoreAspectsAttribute()
    {
        $that = $this;
        return ScoreAspect::all()->map(function($aspect) use ($that) {
            $semester = request('semester') ?? 1;
            $score = $that->scores()->where('score_aspect_id', $aspect->id)->where('semester', $semester)->first();

            $aspect->score = '-';
            $aspect->grade = '-';

            if ($score) {
                $aspect->score = $score->score;
                $aspect->grade = $score->grade;
            }

            return $aspect;
        });
    }

    public function getResultAttribute()
    {
        $semester = request('semester') ?? 1;
        if ($this->scores()->where('semester', $semester)->first()) {
            $average = $this->score_aspects->reduce(function($total, $score) {
                    $total += $score->score;
                    return $total;
                }, 0) / $this->score_aspects->count();

            $grade = '';

            if ($average <= 65) {
                $grade = 'D';
            } else if ($average <= 75) {
                $grade = 'C';
            } else if ($average <= 85) {
                $grade = 'B';
            } else if ($average <= 100) {
                $grade = 'A';
            }

            return [
                'average' => $average,
                'grade' => $grade,
            ];
        }
        return false;
    }
}

app/Models/StudentScore.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class StudentScore extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function getGradeAttribute()
    {
        if ($this->score <= 65) {
            return 'D';
        } else if ($this->score <= 75) {
            return 'C';
        } else if ($this->score <= 85) {
            return 'B';
        } else if ($this->score <= 100) {
            return 'A';
        }
        return null;
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\ScoreAspect;
use App\Models\Student;
use App\Models\StudentScore;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    public function index()
    {
        // get all students sorted by name
        $students = Student::orderBy('name')->get();

        // return view
        return view('student.index', compact('students'));
    }

    public function show(Student $student)
    {
        // return view
        return view('student.show', compact('student'));
    }

    public function grafik(Student $student)
    {
        $students = Student::all()->filter(fn($student) => $student->result);

        $grade = collect([]);
        foreach (['A', 'B', 'C', 'D'] as $i) {
            $grade[$i] = $students->filter(fn($student) => $student->result['grade'] == $i)->count();
        }

        // return view
        return view('student.grafik', compact('student', 'grade'));
    }

    public function create()
    {
        // return view
        return view('student.create');
    }

    public function store(Request $request)
    {
        // validation
        $request->validate([
           'name' => ['required'],
           'email' => ['required', 'unique:students,email'],
           'nim' => ['required', 'unique:students,nim'],
        ]);

        // store
        $student = Student::create($request->only(['name', 'email', 'nim']));

        // response success
        return redirect()->route('students.show', $student)->with('msg', 'Mahasiswa berhasil ditambahkan');
    }

    public function update(Request $request, Student $student)
    {
        foreach ($request->score_aspects as $score_aspect_id => $score) {
            $student->scores()->updateOrCreate([
                'semester' => $request->semester,
                'score_aspect_id' => $score_aspect_id,
            ], [
                'score' => $score
            ]);
        }

        return redirect()->back()->with('msg', 'Nilai berhasil disimpan');
    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">

    <title>Tugas Kelompok 2</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{route('students.index')}}">Tugas Kelompok 2</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{{route('students.index')}}">List Mahasiswa</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{route('students.grafik')}}">Grafik Nilai</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<main class="main">
    @yield('content')
</main>

<script src="{{asset('js/bootstrap.bundle.min.js')}}"></script>
<script src="{{asset('js/chart.js')}}"></script>
@yield('js')
</body>
</html>

resources/views/student/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container py-5">
        <div class="bg-light p-5 mb-5 text-center">
            <h2 class="mb-0">
                Tambah Mahasiswa
            </h2>
        </div>

        @if($errors->all())
            <div class="alert alert-danger">
                <ul style="margin: 0">
                    @foreach($errors->all() as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div style="max-width: 400px; margin: 0 auto;">
            <form action="{{route('students.store')}}" method="POST">
                @csrf
                <div class="form-group mb-2">
                    <label for="nim">NIM</label>
                    <input type="text" id="nim" name="nim" class="form-control">
                </div>
                <div class="form-group mb-2">
                    <label for="name">Nama</label>
                    <input type="text" id="name" name="name" class="form-control">
                </div>
                <div class="form-group mb-3">
                    <label for="email">Email</label>
                    <input type="emaill" id="email" name="email" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary">Tambahkan</button>
            </form>
        </div>
    </div>
@endsection

resources/views/student/grafik.blade.php
@extends('layouts.app')

@section('content')
    <div class="container py-5">

        <div class="mb-5 d-flex align-items-center justify-content-center">
            <label for="semester" class="me-2">Pilih Semester</label>
            <form action="" id="form-semester">
                <select name="semester" id="semester" class="form-control" style="min-width: 80px" onchange="document.getElementById('form-semester').submit()">
                    @foreach(range(1, 7) as $semester)
                        <option {{request('semester') == $semester ? 'selected' : ''}}>{{$semester}}</option>
                    @endforeach
                </select>
            </form>
        </div>

        <div class="card">
            <div class="card-header">
                <h5 class="card-title py-2 mb-0">
                    Grafik Nilai
                </h5>
            </div>
            <div class="card-body">
                <canvas id="grade-chart"></canvas>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script>
        const ctx = document.getElementById('grade-chart').getContext('2d');
        const gradeChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: {!! $grade->keys() !!},
                datasets: [{
                    label: 'Jumlah Mahasiswa',
                    data: {!! $grade->values() !!},
                    backgroundColor: [
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(255, 99, 132, 0.2)'
                    ],
                    borderColor: [
                        'rgba(75, 192, 192, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(255, 99, 132, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true,
                        stepSize: 1
                    }
                }
            }
        });
    </script>
@endsection

resources/views/student/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container py-5">
        <a href="{{route('students.create')}}" class="btn btn-primary mb-3">
            Tambah Mahasiswa
        </a>
        <div class="card">
            <div class="card-header d-flex align-items-center justify-content-between">
                <h5 class="card-title py-2 mb-0">
                    List Mahasiswa
                </h5>
            </div>
            <div class="card-body">
                <table class="table">
                    <thead>
                    <tr>
                        <th>NIM</th>
                        <th>Nama</th>
                        <th>Email</th>
                        <th>Aksi</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($students as $student)
                    <tr>
                        <td>{{$student->nim}}</td>
                        <td>{{$student->name}}</td>
                        <td>{{$student->email}}</td>
                        <td>
                            <a href="{{route('students.show', $student)}}">Lihat Nilai</a>
                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection

resources/views/student/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container py-5">

        @if(session('msg'))
            <div class="alert alert-success mb-5">
                {{session('msg')}}
            </div>
        @endif

        <div class="bg-light p-5 mb-5 text-center">
            <h2 class="mb-1">
                {{$student->name}}
            </h2>
            <span>{{$student->nim}} <span class="mx-1">|</span> {{$student->email}}</span>
        </div>

        <div class="mb-5 d-flex align-items-center justify-content-center">
            <label for="semester" class="me-2">Nilai Semester</label>
            <form action="" id="form-semester">
                <select name="semester" id="semester" class="form-control" style="min-width: 80px" onchange="document.getElementById('form-semester').submit()">
                    @foreach(range(1, 7) as $semester)
                    <option {{request('semester') == $semester ? 'selected' : ''}}>{{$semester}}</option>
                    @endforeach
                </select>
            </form>
        </div>

        <div class="card">
            <div class="card-header">
                <h5 class="card-title py-2 mb-0">
                    List Nilai
                </h5>
            </div>
            <div class="card-body">
                <form action="{{route('students.update', $student)}}" method="POST">
                    <input type="hidden" value="{{request('semester')??1}}" name="semester">
                    @csrf
                    @method('PUT')
                    <table class="table">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Aspek Nilai</th>
                            <th class="text-center">Nilai</th>
                            <th class="text-center">Grade</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($student->score_aspects as $i => $aspect)
                            <tr>
                                <td>{{$i+1}}</td>
                                <td>{{$aspect->name}}</td>
                                <td class="text-center">
                                    <input name="score_aspects[{{$aspect->id}}]" required type="number" min="0" max="100" value="{{$aspect->score}}" class="form-control text-center" style="margin: 0 auto; max-width: 150px">
                                </td>
                                <td class="text-center">{{$aspect->grade}}</td>
                            </tr>
                        @endforeach
                        </tbody>
                        <tfoot>
                        @if($student->result)
                        <tr class="fw-bold">
                            <td></td>
                            <td>Result</td>
                            <td class="text-center">{{$student->result['average']}}</td>
                            <td class="text-center">{{$student->result['grade']}}</td>
                        </tr>
                        @endif
                        </tfoot>
                    </table>
                    <button class="btn btn-primary" type="submit">
                        Simpan Nilai
                    </button>
                </form>
            </div>
        </div>

    </div>
@endsection